In [23]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sbs
import plotly.express as px
from sklearn.preprocessing import StandardScaler,MinMaxScaler,LabelEncoder
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [2]:
year=[2017,2018,2019,2020,2021,2022,2023,2024,2025,2026]
price=[520000,540000,560000,580000,600000,630000,640000,660000,690000,700000]

In [3]:
train_x,test_x,train_y,test_y= train_test_split(year,price,test_size=0.2)

In [4]:
train_x=np.array(train_x).reshape(8,1)

In [5]:
train_y=np.array(train_y).reshape(8,1)

In [6]:
test_x=np.array(test_x).reshape(2,1)

In [7]:
test_y=np.array(test_y).reshape(2,1)

In [8]:
lr=LinearRegression()

In [9]:
lr.fit(train_x,train_y)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [10]:
m=lr.coef_

In [11]:
c= lr.intercept_

In [12]:
h= test_x [:1]

In [13]:
(m*h)+c

array([[601974.52229299]])

# to check the performance of the model

In [14]:
pred=lr.predict(test_x)

In [15]:
MSE= mean_squared_error(test_y,pred)

In [16]:
RMSE= MSE**0.5

In [17]:
R_square= r2_score(test_y,pred)

In [18]:
MAE= mean_absolute_error(test_y,pred)

In [19]:
print(MSE) 
print(RMSE)
print(R_square) # how much we are improving by using linear model instead of doing prediction on average
print(MAE)

1955003.8090347757
1398.2145075183478
0.9987781226193533
1040.339702758938


In [22]:
1-((1-R_square)*(len(year)-1))/(len(year)-1-1)    # adjusted r_squared value

0.9986253879467725

In [24]:
L1= Ridge()
L2= Lasso()
EN= ElasticNet()

In [25]:
L1.fit(train_x,train_y)
L2.fit(train_x,train_y)
EN.fit(train_x,train_y)

,"alpha alpha: float, default=1.0Constant that multiplies the penalty terms. Defaults to 1.0.See the notes for the exact mathematical meaning of thisparameter. ``alpha = 0`` is equivalent to an ordinary least square,solved by the :class:`LinearRegression` object. For numericalreasons, using ``alpha = 0`` with the ``Lasso`` object is not advised.Given this, you should use the :class:`LinearRegression` object.",1.0
,"l1_ratio l1_ratio: float, default=0.5The ElasticNet mixing parameter, with ``0 <= l1_ratio <= 1``. For``l1_ratio = 0`` the penalty is an L2 penalty. ``For l1_ratio = 1`` itis an L1 penalty. For ``0 < l1_ratio < 1``, the penalty is acombination of L1 and L2.",0.5
,"fit_intercept fit_intercept: bool, default=TrueWhether the intercept should be estimated or not. If ``False``, thedata is assumed to be already centered.",True
,"precompute precompute: bool or array-like of shape (n_features, n_features), default=FalseWhether to use a precomputed Gram matrix to speed upcalculations. The Gram matrix can also be passed as argument.For sparse input this option is always ``False`` to preserve sparsity.Check :ref:`an example on how to use a precomputed Gram Matrix in ElasticNet`for details.",False
,"max_iter max_iter: int, default=1000The maximum number of iterations.",1000
,"copy_X copy_X: bool, default=TrueIf ``True``, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-4The tolerance for the optimization: if the updates are smaller or equal to``tol``, the optimization code checks the dual gap for optimality and continuesuntil it is smaller or equal to ``tol``, see Notes below.",0.0001
,"warm_start warm_start: bool, default=FalseWhen set to ``True``, reuse the solution of the previous call to fit asinitialization, otherwise, just erase the previous solution.See :term:`the Glossary `.",False
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive.",False
,"random_state random_state: int, RandomState instance, default=NoneThe seed of the pseudo random number generator that selects a randomfeature to update. Used when ``selection`` == 'random'.Pass an int for reproducible output across multiple function calls.See :term:`Glossary `.",None
,"selection selection: {'cyclic', 'random'}, default='cyclic'If set to 'random', a random coefficient is updated every iterationrather than looping over features sequentially by default. This(setting to 'random') often leads to significantly faster convergenceespecially when tol is higher than 1e-4.",'cyclic'


In [27]:
print(L1.score(train_x,train_y))
print(L2.score(train_x,train_y))
print(EN.score(train_x,train_y))

0.9485264834726987
0.9919336690095766
0.9485229489561057


In [28]:
print(L1.score(test_x,test_y))
print(L2.score(test_x,test_y))
print(EN.score(test_x,test_y))

0.9876543209876566
0.99999999984375
0.9876530863888819


In [32]:
L2.predict(test_x)

array([599999.5, 520000.5])

In [38]:
L1.predict(test_x)

array([595555.55555555, 524444.44444444])

In [35]:
EN.predict(test_x)

array([595555.33333334, 524444.66666667])

In [39]:
test_y

array([[600000],
       [520000]])