In [55]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sbs
import plotly.express as px
from sklearn.preprocessing import StandardScaler,MinMaxScaler,LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# LINEAR REGRESSION

# Predict only numbers [Regression problem ko solve kr skta hai]

In [2]:
# prediction = m*x + c
# m=slope, c= intercept

In [3]:
# if i wanted to predict weight on basis of height 
# M * height + c = weight

In [4]:
x=[150,152,154,156,158,160,162,164,166,168]
weight=[50,52,54,56,58,60,62,64,66,68]

In [5]:
# training contains 70% of the data and testing includes 30% of the data

In [6]:
test_x= np.array([x[:3]]).reshape(3,1)
test_y= weight[:3]

In [7]:
train_x= np.array([x[3:]]).reshape(7,1)
train_y=weight[3:]

In [8]:
# MODEL

In [9]:
lr= LinearRegression()

In [10]:
lr.fit(train_x,train_y)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [11]:
train_x

array([[156],
       [158],
       [160],
       [162],
       [164],
       [166],
       [168]])

In [12]:
train_y

[56, 58, 60, 62, 64, 66, 68]

In [13]:
M= lr.coef_

In [14]:
c= lr.intercept_

In [15]:
h= test_x[2]

In [16]:
weight=M*h+c

In [17]:
weight

array([54.])

In [19]:
#Regression= number prediction
#X= car purchase year 
#y= Car price

In [20]:
year=[2017,2018,2019,2020,2021,2022,2023,2024,2025,2026]
price=[520000,540000,560000,580000,600000,620000,640000,660000,680000,700000]

In [29]:
lr=LinearRegression()

In [30]:
lr.fit(train_x,train_y)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [37]:
m=lr.coef_

In [45]:
h= test_x[2]

In [46]:
c= lr.intercept_

In [47]:
price=m*h+c

In [48]:
price

array([560000.])